app/models.py
from app import db

class Usuario(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(10), unique=True, nullable=False)
    password_hash = db.Column(db.String(100), nullable=False) #TO DO: recibir hash
    role = db.Column(db.String(10), nullable=False)


class Compra:
    def __init__(self, nombre:str='', edad:str='', tarros:str=''):
        self.nombre = nombre
        self.edad = edad
        self.tarros = tarros

    def set_compra(self, nombre:str, edad:int, tarros:int):
        self.nombre = nombre
        self.edad = edad
        self.tarros = tarros
    def get_compra(self)->dict:
        return {
            'nombre' : self.nombre,
            'edad' : self.edad,
            'tarros' : self.tarros,
                }

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

def create_app():
    '''Inicialización de aplicación'''
    app = Flask(__name__,template_folder='templates')

    #Configurar base de datos
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///dev.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    #Importar rutas
    from .routes import app_routes
    app.register_blueprint(app_routes)
    return app

app/routes.py
from flask import Blueprint, render_template,request
from app.methods import *

app_routes = Blueprint('app_routes', __name__)


# RUTAS:
@app_routes.route('/')
def home():
    return render_template('home.html')

@app_routes.route('/ejercicio1', methods=['GET', 'POST'])
def ej1():
    print("LOG: ruta //ejercicio1 ejecutada")
    errores:list = []
    cotizacion = obener_formulario(request.form.to_dict()) if request.method == 'POST' else Compra()
    resultado = None

    if request.method == 'POST':
        # Validación
        print("LOG: Validación campos vacíos y rangos")
        campos_vacios:list[str] = validar_campo_vacio(cotizacion.get_compra())
        if campos_vacios:
            errores.append(f"Campos vacíos: {', '.join(campos_vacios)}")
        if not campos_vacios:
            if cotizacion.edad and (not cotizacion.edad.isdigit() or int(cotizacion.edad) <= 0):
                errores.append("La edad debe ser un número mayor a 0.")
            if cotizacion.tarros and (not cotizacion.tarros.isdigit() or int(cotizacion.tarros) <= 0):
                errores.append("La cantidad de tarros debe ser un número mayor a 0.")
        print("LOG: Validación completada")
        if not errores:
            cotizacion.edad = int(cotizacion.edad)
            cotizacion.tarros = int(cotizacion.tarros)
            valor_tarros:int = 9000

            # Procesar datos
            total_sinDescuento:int = calc_total(cotizacion.tarros, valor_tarros)
            descuento:float = calc_descuento(cotizacion.edad, total_sinDescuento)
            total_pagar:float = calc_totalPagar(cotizacion.edad,total_sinDescuento, descuento)

            resultado = {
                'Nombre del cliente': fr' ${cotizacion.nombre}',
                'Total sin descuento': fr' ${total_sinDescuento}',
                'El descuento es': fr' {descuento}',
                'El total a pagar es de' : fr'{total_pagar}'
            }
    return render_template('ejercicio1.html',
                           datos=cotizacion.get_compra(),
                           errores=errores,
                           resultado=resultado)

@app_routes.route('/ejercicio2', methods=['GET', 'POST'])
def ej2():
    print("LOG: ruta /ejercicio2 ejecutada")
    mensaje = None
    errores:list = []
    datos:dict ={'usuario':'', 'password':''}

    if request.method == 'POST':
        # Obtener datos de formulario
        datos['usuario'] = request.form.get('usuario','').strip()
        datos['password'] = request.form.get('password','').strip()

        # Validación
        campos_vacios = validar_campo_vacio(datos)
        if campos_vacios:
            errores.append("Campos vacíos: {', '.join(campos_vacios)}")
        else:
            user = Usuario.query.filter_by(username=datos['usuario']).first()
            if user and chk_password_usuario(user, datos['password']):
                mensaje = f"Bienvenido {user.role} {user.username}"
            else:
                mensaje = f"Usuario o contraseña incorrectos"
    return render_template('ejercicio2.html',
                           datos = datos,
                           mensaje=mensaje,
                           errores=errores)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Página Base {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/styles.css') }}">
    <script src="{{ url_for('static',filename='js/scripts.js') }}" defer></script>
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

app/templates/ejercicio1.html
{% extends "base.html" %}
{% block title %}Calculo de compras{% endblock %}
{% block content %}
    <div class="container">
        <h2>Calculo de compras</h2>
        <form novalidate action="{{ url_for('app_routes.ej1') }}" method="post">
            <label for="nombre">Ingresa tu nombre</label>
            <input class="inputCampo" type="text" id="nombre" name="nombre"
                value="{{ datos['nombre'] }}">
            <br><br>

            <label for="edad">Ingresa tu edad</label>
            <input class="inputCampo" type="number" id="edad" name="edad" min="1"
                value="{{ datos['edad'] }}">
            <br><br>

            <label for="tarros">Ingresa la cantidad de tarros de pintura a comprar</label>
            <input class="inputCampo" type="number" id="tarros" name="tarros" min="1"
                value="{{ datos['tarros'] }}">
            <br><br>

            <input class="btn-submit" type="submit" value="Calcular" >
        </form>
        <!-- Errores: -->
        <p id="msgError" style="color: red"></p>

        {% if errores %}
            <ul id="msgError" style="color: red;">
                {% for error in errores %}
                    <li >{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if resultado is not none %}
            {% for clave, valor in resultado.items() %}
                <p class="resultado">{{ clave }}:{{ valor }}</p>
            {% endfor %}
        {% endif %}

    </div>
{% endblock %}

app/templates/ejercicio2.html
{% extends "base.html" %}
{% block title %}Inicio de sesión{% endblock %}
{% block content %}
    <div class="container">
        <h2>Inicio de sesión</h2>
        <form novalidate action="{{ url_for('app_routes.ej2') }}" method="post">
            <label for="usuario">Ingresa tu nombre</label>
            <input class="inputCampo" type="text" id="usuario" name="usuario"
                value="{{ datos['usuario'] }}">
            <br><br>

            <label for="password">Ingresa tu contraseña</label>
            <input class="inputCampo" type="password" id="password" name="password"
                value="{{ datos['password'] }}">
            <br><br>

            <input class="btn-submit" type="submit" value="Verificar" >
        </form>
        <!-- Errores: -->
        <p id="msgError" style="color: red"></p>
        {% if errores %}
            <ul id="msgError" style="color: red;">
                {% for error in errores %}
                    <li >{{ errore }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if mensaje %}
            <p class="resultado">{{ mensaje }}</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock %}
{% block content %}
    <div class="home-container">
        <a class="home-button" id="btnEjercicio1" href="{{ url_for('app_routes.ej1') }}">Ejercicio 1</a>
        <a class="home-button" id="btnEjercicio2" href="{{ url_for('app_routes.ej2') }}">Ejercicio 2</a>
    </div>
{% endblock %}